/**
 * Scans configured sources, writes WebP + TIFF under public/optimized/,
 * and regenerates content/images-manifest.md for the /api/images route.
 */
import fs from "fs/promises";
import path from "path";
import sharp from "sharp";

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, "public");
const OPTIMIZED_DIR = path.join(PUBLIC_DIR, "optimized");
const TIFF_DIR = path.join(OPTIMIZED_DIR, "tiff");
const MANIFEST_PATH = path.join(ROOT, "content", "images-manifest.md");
const GALLERY_CONFIG = path.join(ROOT, "content", "gallery.json");

const MAX_WIDTH = 1920;
const WEBP_QUALITY = 82;

interface SourceEntry {
  id: number;
  group: string;
  type: "image" | "video";
  title: string;
  desc: string;
  original: string;
}

interface ManifestEntry {
  id: number;
  group: string;
  type: "image" | "video";
  title: string;
  desc: string;
  original: string;
  url: string;
  tiffUrl: string;
  width: number;
  height: number;
  originalBytes: number;
  optimizedBytes: number;
  tiffBytes: number;
}

async function resolvePublicFile(urlPath: string): Promise<string | null> {
  const base = path.basename(urlPath);
  const entries = await fs.readdir(PUBLIC_DIR);
  const match = entries.find((f) => f.toLowerCase() === base.toLowerCase());
  if (!match) return null;
  return path.join(PUBLIC_DIR, match);
}

function slugFromPath(urlPath: string): string {
  return path.basename(urlPath, path.extname(urlPath)).toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

async function optimizeImage(
  sourcePath: string,
  slug: string
): Promise<{
  url: string;
  tiffUrl: string;
  width: number;
  height: number;
  optimizedBytes: number;
  tiffBytes: number;
}> {
  const webpFile = `${slug}.webp`;
  const tiffFile = `${slug}.tif`;
  const webpPath = path.join(OPTIMIZED_DIR, webpFile);
  const tiffPath = path.join(TIFF_DIR, tiffFile);

  const pipeline = sharp(sourcePath).rotate().resize({
    width: MAX_WIDTH,
    withoutEnlargement: true,
  });

  const meta = await sharp(sourcePath).metadata();

  await pipeline.clone().webp({ quality: WEBP_QUALITY }).toFile(webpPath);
  await pipeline
    .clone()
    .tiff({ compression: "lzw", predictor: "horizontal" })
    .toFile(tiffPath);

  const [webpStat, tiffStat] = await Promise.all([
    fs.stat(webpPath),
    fs.stat(tiffPath),
  ]);

  return {
    url: `/optimized/${webpFile}`,
    tiffUrl: `/optimized/tiff/${tiffFile}`,
    width: meta.width ?? 0,
    height: meta.height ?? 0,
    optimizedBytes: webpStat.size,
    tiffBytes: tiffStat.size,
  };
}

async function buildManifestMarkdown(images: ManifestEntry[]): Promise<string> {
  const generatedAt = new Date().toISOString();
  const saved = Math.round(
    images.reduce((sum, i) => sum + (i.originalBytes - i.optimizedBytes), 0) / 1024
  );

  return `---
generatedAt: ${generatedAt}
totalImages: ${images.length}
savedKb: ${saved}
---

# Portfolio image manifest

Auto-generated by \`npm run images:generate\`. Do not edit the JSON block by hand.

- **url** — WebP served to the browser (fast load in production)
- **tiffUrl** — LZW-compressed TIFF (archival / API download; limited browser support)

\`\`\`json
${JSON.stringify(images, null, 2)}
\`\`\`
`;
}

async function main() {
  await fs.mkdir(OPTIMIZED_DIR, { recursive: true });
  await fs.mkdir(TIFF_DIR, { recursive: true });

  const raw = await fs.readFile(GALLERY_CONFIG, "utf-8");
  const sources = JSON.parse(raw) as SourceEntry[];
  const manifest: ManifestEntry[] = [];

  for (const entry of sources) {
    if (entry.type === "video") {
      manifest.push({
        ...entry,
        url: entry.original,
        tiffUrl: "",
        width: 0,
        height: 0,
        originalBytes: 0,
        optimizedBytes: 0,
        tiffBytes: 0,
      });
      continue;
    }

    const sourcePath = await resolvePublicFile(entry.original);
    if (!sourcePath) {
      console.warn(`⚠ Skipping missing file: ${entry.original}`);
      continue;
    }

    const slug = slugFromPath(entry.original);
    const originalStat = await fs.stat(sourcePath);
    const optimized = await optimizeImage(sourcePath, slug);

    manifest.push({
      id: entry.id,
      group: entry.group,
      type: entry.type,
      title: entry.title,
      desc: entry.desc,
      original: entry.original,
      ...optimized,
      originalBytes: originalStat.size,
    });

    const savedPct = (
      ((originalStat.size - optimized.optimizedBytes) / originalStat.size) *
      100
    ).toFixed(1);
    console.log(
      `✓ ${entry.title}: ${(originalStat.size / 1024 / 1024).toFixed(1)}MB → WebP ${(optimized.optimizedBytes / 1024).toFixed(0)}KB (${savedPct}% smaller)`
    );
  }

  manifest.sort((a, b) => a.id - b.id);
  await fs.writeFile(MANIFEST_PATH, await buildManifestMarkdown(manifest), "utf-8");
  console.log(`\nWrote ${MANIFEST_PATH} (${manifest.length} images)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
